// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCx3iFIqR3w7AmEEjSR43j1SasdJZey4A8',
    appId: '1:434065058254:web:1c2a076211f1d7a3de239f',
    messagingSenderId: '434065058254',
    projectId: 'nebula-9fa81',
    authDomain: 'nebula-9fa81.firebaseapp.com',
    storageBucket: 'nebula-9fa81.firebasestorage.app',
    measurementId: 'G-W9QZ5JC939',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPojAwwm11VFZ6ZPe8ONvbuXNWYRRVOR8',
    appId: '1:434065058254:android:767fa6bd31c92fbdde239f',
    messagingSenderId: '434065058254',
    projectId: 'nebula-9fa81',
    storageBucket: 'nebula-9fa81.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvV3d9mQfDOPxOJlEgO8G-sQprOYh_2lo',
    appId: '1:434065058254:ios:134acb36d4c5a185de239f',
    messagingSenderId: '434065058254',
    projectId: 'nebula-9fa81',
    storageBucket: 'nebula-9fa81.firebasestorage.app',
    iosBundleId: 'com.example.nebula',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvV3d9mQfDOPxOJlEgO8G-sQprOYh_2lo',
    appId: '1:434065058254:ios:134acb36d4c5a185de239f',
    messagingSenderId: '434065058254',
    projectId: 'nebula-9fa81',
    storageBucket: 'nebula-9fa81.firebasestorage.app',
    iosBundleId: 'com.example.nebula',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCx3iFIqR3w7AmEEjSR43j1SasdJZey4A8',
    appId: '1:434065058254:web:debf89840e04acf6de239f',
    messagingSenderId: '434065058254',
    projectId: 'nebula-9fa81',
    authDomain: 'nebula-9fa81.firebaseapp.com',
    storageBucket: 'nebula-9fa81.firebasestorage.app',
    measurementId: 'G-Q76J2MFEBY',
  );
}
